# Generated by Django 3.2.6 on 2021-10-01 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_answerkey',
            fields=[
                ('kid', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='exam_exam',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('max_point', models.FloatField(default=10)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.TextField(max_length=700)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('take', models.IntegerField(default=3)),
                ('time', models.TimeField(default=0)),
                ('code', models.IntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='exam_question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('max_point', models.FloatField(default=0)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=500)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baitap.exam_exam')),
            ],
        ),
        migrations.CreateModel(
            name='exam_primarykey',
            fields=[
                ('pkid', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.FloatField(default=0)),
                ('pkey', models.TextField(default='')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baitap.exam_answerkey')),
            ],
        ),
        migrations.AddField(
            model_name='exam_answerkey',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baitap.exam_question'),
        ),
        migrations.CreateModel(
            name='exam_answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(default='', max_length=700)),
                ('point', models.FloatField(default=0)),
                ('create', models.DateField(auto_now_add=True)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baitap.exam_question')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
