# Generated by Django 3.2.6 on 2021-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baitap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_exam',
            name='create',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exam_exam',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exam_exam',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
    ]
