# Generated by Django 3.2.6 on 2021-10-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baitap', '0002_auto_20211001_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_exam',
            name='create',
            field=models.TimeField(default=0),
        ),
    ]
