# Generated by Django 3.2.6 on 2021-10-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baitap', '0005_exam_question_answergv'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_question',
            name='cauhoi',
            field=models.IntegerField(default=1),
        ),
    ]
