# Generated by Django 3.2.6 on 2021-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baitap', '0003_alter_exam_exam_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_exam',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
