# Generated by Django 3.2.6 on 2021-12-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baitap', '0005_exam_question_answergv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_answer',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exam_question',
            name='answergv',
            field=models.TextField(blank=True, default='', max_length=700),
        ),
    ]
